name: Cache and artifcats for application

on:
 push:
  branches: [ main ]

jobs:
  Cache_and_artifacts:
   runs-on: ubuntu-latest

   concurrency:
     group: deploy
     cancel-in-progress: true

   steps:
     - name: Checkout Repository
       uses: actions/checkout@v4

     - name: Install dependencies
       run: npm install

     - name: Build app
       run: npm run build
     - name: Sleep
       run: sleep 30
     - name: Final Message
       run: echo "workflow completed"
       
       
