name: Cache and artifcats for application

on:
 push:
  branches: [ main ]

jobs:
  Cache_and_artifacts:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout Repository
       uses: actions/checkout@v4

     - name: setup node js
       uses: actions/setup-node@v6.5.0
       with:
        node-version: 22.x
        cache: "npm"

     - name: Install dependencies
       run: npm install

     - name: Build app
       run: npm run build

     - name: Artificats collection
       uses: actions/upload-artifact@v7.0.1
       with:
        name: next js build
        path: ./dist/
       
       
